const certificates = [
    {   
        title: "Project Initiation: Starting a Successful Project",
        issuingOrganization: "Google",
        credentialURL: "https://www.coursera.org/account/accomplishments/certificate/JK3HLJZK36R3",
        learningObjectives: [
            "Define and create measurable project goals and deliverables",
            "Define project scope and differentiate among tasks that are in-scope and out-of-scope",
            "Explain how to manage scope creep to avoid impacting project goals",
            "Define and measure a project’s success criteria",
            "Define project roles and responsibilities",
            "Complete a stakeholder analysis and explain its significance",
            "Utilize RACI charts to define and communicate project team member responsibilities",
            "Outline the typical resources needed to manage a project",
            "Identify the key components of project charters and develop a project charter for project initiation",
            "Evaluate various project management tools to meet project needs",
        ],
    },
    {   
        title: "Foundations of Project Management",
        issuingOrganization: "Google",
        credentialURL: "https://www.coursera.org/account/accomplishments/certificate/E87WLV2MGY55",
        learningObjectives: [
            "Relate the skills and responsibilities of a project manager necessary to achieve success on the job",
            "Define project management and describe what constitutes a project",
            "Explain project management roles and responsibilities across a variety of industries",
            "Detail and relate project management skills to project management and its value to business",
            "Detail the core skills to be a successful project manager",
            "Describe the role and day-to-day responsibilities of a project manager",
            "Discuss when and why it is necessary to have a project manager",
            "Explain why it is important to understand and follow the life cycle of a project",
            "Define and outline a project’s phases and each phase’s tasks",
            "Compare different program management methodologies and determine which is most effective for a given project",
            "Define change management and summarize its relationship to the project management role",
            "Define organizational culture and explain how it impacts project management",
            "Identify common types of organizational structures",
            "Define organizational structure and explain how it impacts project management",
        ],
    },
    {   
        title: "Kotlin for Java Developers",
        issuingOrganization: "JetBrains",
        credentialURL: "https://www.coursera.org/account/accomplishments/certificate/8JUG3979ZUYW",
        learningObjectives: [
            "List the key characteristics of Kotlin",
            "Understand the types of tasks where Kotlin can be used",
            "Convert Java code to Kotlin automatically",
            "Define variables and functions",
            "Use control structures",
            "Employ ranges",
            "Explain what is an extension function in Kotlin",
            "Define and use extensions",
            "Distinguish nullable types and non-nullable types",
            "Use different ways to perform an action only when a value of a nullable type is not null",
            "Prefer safe operations for nullable values",
            "Employ functional programming style for manipulating collections",
            "Use function types",
            "Choose the right form of return expression for returning from lambda",
            "Distinguish between different kinds of properties: without backing field, lazy, lateinit",
            "Summarize the differences in defining and using classes with Java",
            "Know the different syntax for constructors",
            "Use different kinds of classes for correct situations: enum, data, inner, sealed",
            "Use annotations to improve Java interoperability",
            "Explain the difference between object expression and object declaration",
            "Show the benefits of companion objects over static methods",
            "Give examples of using conventions in the standard library",
            "Employ conventions for your own classes",
            "Use short simple function from the standard library",
            "Explain why simple library functions bring no performance overhead",
            "Demonstrate how inlining works",
            "Describe the difference between operations on Collections and operations on Sequences",
            "Convert a chained call from Collections to Sequences",
            "Recognize lambdas with receiver in the code: in the standard library and different DSLs",
            "Illustrate in what sense lambdas with receiver are similar to extensions",
            "Show the Kotlin type hierarchy",
            "Explain the difference between Unit and Nothing types",
            "Recognize platform types: the types that came from Java",
            "Prevent NPEs for mixed Kotlin and Java code",
        ],
    },
    {   
        title: "Introduction to Machine Learning in Production",
        issuingOrganization: "DeepLearning.AI",
        credentialURL: "https://www.coursera.org/account/accomplishments/certificate/CYPPNN5AUARM",
        learningObjectives: [
            "Identify the key components of the ML Lifecycle",
            "Define concept drift as it relates to ML projects",
            "Differentiate between shadow, canary, and blue-green deployment scenarios in the context of varying degrees of automation",
            "Compare and contrast the ML modeling iterative cycle with the cycle for deployment of ML products",
            "List the typical metrics you might track to monitor concept drift",
            "Identify the key challenges in model development",
            "Describe how performance on a small set of disproportionately important examples may be more crucial than performance on the majority of examples",
            "Explain how rare classes in your training data can affect performance",
            "Define three ways of establishing a baseline for your performance",
            "Define structured vs. unstructured data",
            "Identify when to consider deployment constraints when choosing a model",
            "List the steps involved in getting started with ML modeling",
            "Describe the iterative process for error analysis",
            "Identify the key factors in deciding what to prioritize when working to improve model accuracy",
            "Describe methods you might use for data augmentation given audio data vs. image data",
            "Explain the problems you can have training on a highly skewed dataset",
            "Identify a use case in which adding more data to your training dataset could actually hurt performance",
            "Describe the key components of experiment tracking",
            "List the questions you need to answer in the process of data definition",
            "Compare and contrast the types of data problems you need to solve for structured vs. unstructured and big vs. small data",
            "Explain why label consistency is important and how you can improve it",
            "Explain why beating human level performance is not always indicative of success of an ML model",
            "Make a case for improving human level performance rather than beating it",
            "Identify how much training data you should gather given time and resource constraints",
            "Describe the key steps in a data pipeline",
            "Compare and contrast the proof of concept vs. production phases on an ML project",
            "Explain the importance of keeping track of data provenance and lineage",
        ],
    },
    {   
        title: "Mindshift: Break Through Obstacles to Learning and Discover Your Hidden Potential",
        issuingOrganization: "McMaster University",
        credentialURL: "https://www.coursera.org/account/accomplishments/certificate/3YSEUSK8LZ9H",
        learningObjectives: [
        ],
    },
    {   
        title: "Learning How to Learn: Powerful mental tools to help you master tough subjects",
        issuingOrganization: "Deep Teaching Solutions",
        credentialURL: "https://www.coursera.org/account/accomplishments/certificate/7V8GTJZPECPE",
        learningObjectives: [
        ],
    },
    {   
        title: "Writing in the Sciences",
        issuingOrganization: "Stanford University",
        credentialURL: "https://www.coursera.org/account/accomplishments/certificate/BXQFF76H5AP3",
        learningObjectives: [
            "Practice removing clutter from writing",
            "Practice writing clearly and concisely",
            "Distinguish between active and passive verbs",
            "Practice writing with strong, active verbs",
            "Fix sentences where the subject and predicate are too far apart",
            "Correct specific grammar mistakes",
            "Practice using colons, dashes, parentheses, and semi-colons",
            "Recognize the importance of varying sentence structure",
            "Practice writing focused, organized paragraphs",
            "Recognize that it is OK to repeat key words in scientific writing",
            "Fix sentence parallelism",
            "Practice writing clear and concise paragraphs",
            "Describe the steps in the writing process",
            "Recognize the importance of spending sufficient time pre-writing",
            "Recognize that good writing requires extensive revision",
            "Understand how to write the sections of an original scientific manuscript",
            "Critique poorly formatted tables and figures",
            "Practice writing strong Results and Introduction sections",
            "Summarize the elements of a Discussion section",
            "Identify and avoid plagiarism",
            "Understand the peer review process",
            "Understand criteria for authorship",
            "Recognize common pitfalls for new authors",
            "Recognize predatory journals",
            "Identify and avoid plagiarism",
            "Understand the peer review process",
            "Understand criteria for authorship",
            "Recognize common pitfalls for new authors",
            "Recognize predatory journals",
            "Recognize the importance of communicating science with broader audiences",
            "Be prepared to be interviewed by a journalist",
            "Recognize the difference between writing for scientific audiences and writing for lay audiences",
            "Understand the structure of a science news story",
            "Learn tips for how to interview a scientist",
        ],
    },
];

export default certificates;